# MPLAB IDE generated this makefile for use with GNU make.
# Project: USB Device - HID - Simple Custom Demo - C18 - PICDEM FSUSB.mcp
# Date: Fri Feb 07 10:53:13 2014

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo\ -\ C18\ -\ PICDEM\ FSUSB.cof : Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/usb_descriptors.o Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/usb_function_hid.o Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/usb_device.o Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/main_TMS.o
	$(LD) /l"C:\mcc18\lib" "rm18f4550.lkr" "Objects\USB Device - HID - Simple Custom Demo\usb_descriptors.o" "Objects\USB Device - HID - Simple Custom Demo\usb_function_hid.o" "Objects\USB Device - HID - Simple Custom Demo\usb_device.o" "Objects\USB Device - HID - Simple Custom Demo\main_TMS.o" /u_CRUNTIME /u_DEBUG /u_DEBUGCODESTART=0x7dc0 /u_DEBUGCODELEN=0x240 /u_DEBUGDATASTART=0x3f4 /u_DEBUGDATALEN=0xc /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /z__MPLAB_DEBUGGER_ICD2=1 /z__ICD2RAM=1 /m"USB Device - HID - Simple Custom Demo - C18 - PICDEM FSUSB.map" /w /o"USB Device - HID - Simple Custom Demo - C18 - PICDEM FSUSB.cof"

Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/usb_descriptors.o : usb_descriptors.c c:/mcc18/h/stdio.h c:/mcc18/h/stdlib.h c:/mcc18/h/string.h ../../Microchip/Include/USB/usb_common.h ../../Microchip/Include/USB/usb_device.h usb_descriptors.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h c:/mcc18/h/p18cxxx.h c:/mcc18/h/p18f4550.h c:/mcc18/h/stdarg.h c:/mcc18/h/stddef.h usb_config.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/usb_hal.h c:/mcc18/h/limits.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb_function_hid.h
	$(CC) -p=18F4550 /i"." -I".." -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Simple Custom Demo" -I"..\..\..\USB Device - HID - Simple Custom Demo" "usb_descriptors.c" -fo=".\Objects\USB Device - HID - Simple Custom Demo\usb_descriptors.o" -D__DEBUG -D__MPLAB_DEBUGGER_ICD2=1 -pa=4

Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/usb_function_hid.o : ../../Microchip/USB/HID\ Device\ Driver/usb_function_hid.c c:/mcc18/h/stdio.h c:/mcc18/h/stdlib.h c:/mcc18/h/string.h ../../Microchip/Include/USB/usb_common.h ../../Microchip/Include/USB/usb_device.h ../../Microchip/USB/HID\ Device\ Driver/usb_function_hid.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h c:/mcc18/h/p18cxxx.h c:/mcc18/h/p18f4550.h c:/mcc18/h/stdarg.h c:/mcc18/h/stddef.h usb_config.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/usb_hal.h c:/mcc18/h/limits.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb_function_hid.h
	$(CC) -p=18F4550 /i"." -I".." -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Simple Custom Demo" -I"..\..\..\USB Device - HID - Simple Custom Demo" "..\..\Microchip\USB\HID Device Driver\usb_function_hid.c" -fo=".\Objects\USB Device - HID - Simple Custom Demo\usb_function_hid.o" -D__DEBUG -D__MPLAB_DEBUGGER_ICD2=1 -pa=4

Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/usb_device.o : ../../Microchip/USB/usb_device.c c:/mcc18/h/stdio.h c:/mcc18/h/stdlib.h c:/mcc18/h/string.h ../../Microchip/Include/usb/usb_common.h ../../Microchip/Include/usb/usb_device.h ../../Microchip/USB/usb_device.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h c:/mcc18/h/p18cxxx.h c:/mcc18/h/p18f4550.h c:/mcc18/h/stdarg.h c:/mcc18/h/stddef.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/USB.h usb_config.h c:/mcc18/h/limits.h ../../Microchip/Include/usb/usb_ch9.h ../../Microchip/Include/usb/usb_hal.h ../../Microchip/Include/USB/usb_common.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb_hal.h ../../Microchip/Include/USB/usb_device.h HardwareProfile.h HardwareProfile\ -\ PICDEM\ FSUSB.h
	$(CC) -p=18F4550 /i"." -I".." -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Simple Custom Demo" -I"..\..\..\USB Device - HID - Simple Custom Demo" "..\..\Microchip\USB\usb_device.c" -fo=".\Objects\USB Device - HID - Simple Custom Demo\usb_device.o" -D__DEBUG -D__MPLAB_DEBUGGER_ICD2=1 -pa=4

Objects/USB\ Device\ -\ HID\ -\ Simple\ Custom\ Demo/main_TMS.o : main_TMS.c c:/mcc18/h/stdio.h c:/mcc18/h/stdlib.h c:/mcc18/h/string.h ../../Microchip/Include/USB/usb_common.h ../../Microchip/Include/USB/usb_device.h c:/mcc18/h/USART.h main_TMS.c ../../Microchip/Include/GenericTypeDefs.h ../../Microchip/Include/Compiler.h c:/mcc18/h/p18cxxx.h c:/mcc18/h/p18f4550.h c:/mcc18/h/stdarg.h c:/mcc18/h/stddef.h usb_config.h ../../Microchip/Include/USB/usb_ch9.h ../../Microchip/Include/USB/usb_hal.h c:/mcc18/h/limits.h ../../Microchip/Include/USB/usb_hal_pic18.h ../../Microchip/Include/USB/usb.h ../../Microchip/Include/usb/usb_common.h ../../Microchip/Include/usb/usb_ch9.h ../../Microchip/Include/usb/usb_hal.h ../../Microchip/Include/usb/usb_device.h HardwareProfile.h HardwareProfile\ -\ PICDEM\ FSUSB.h ../../Microchip/Include/USB/usb_function_hid.h c:/mcc18/h/pconfig.h
	$(CC) -p=18F4550 /i"." -I".." -I"..\..\Include" -I"..\..\..\Include" -I"..\..\Microchip\Include" -I"..\..\USB Device - HID - Simple Custom Demo" -I"..\..\..\USB Device - HID - Simple Custom Demo" "main_TMS.c" -fo=".\Objects\USB Device - HID - Simple Custom Demo\main_TMS.o" -D__DEBUG -D__MPLAB_DEBUGGER_ICD2=1 -pa=4

clean : 
	$(RM) "Objects\USB Device - HID - Simple Custom Demo\usb_descriptors.o" "Objects\USB Device - HID - Simple Custom Demo\usb_function_hid.o" "Objects\USB Device - HID - Simple Custom Demo\usb_device.o" "Objects\USB Device - HID - Simple Custom Demo\main_TMS.o" "USB Device - HID - Simple Custom Demo - C18 - PICDEM FSUSB.cof" "USB Device - HID - Simple Custom Demo - C18 - PICDEM FSUSB.hex" "USB Device - HID - Simple Custom Demo - C18 - PICDEM FSUSB.map"

